### ISSUE TITLE
When there are 4 or less slides with wrapAround, transition is broken

### ISSUE THREAD

**Issue by LucianHij** [ismail9k/vue3-carousel#120] opened 2021-11-08 22:42 UTC
https://codesandbox.io/s/ncpb8

The issue is seen in the codesandbox. When swiping the transition is broken.

**Comment by omni-frontend-dev** [comment] 2021-11-11 20:18
Transition from does break when there are 4 or less.

**Comment by lackoSK** [comment] 2021-11-12 12:36
I can confirm the issue is present, four or fewer slides - the transition is not behaving as supposed.

**Comment by sonjinh9862** [comment] 2021-11-19 16:32
if there a four slides, transition got breaking. it must to slide right to left but reversed.

**Comment by LucianHij** [comment] 2021-11-20 07:01
@ismail9k are you still maintaining this package? Or we should search for another solution outthere?

**Comment by fyapy** [comment] 2021-11-30 04:29
This issue has been fixed in `v0.1.32`

**Closed** 2021-11-30 08:11 UTC

**Comment by GeorgyLevin** [comment] 2021-12-23 15:59
> This issue has been fixed in `v0.1.32`

Its not. With 2 slides and warpAround=true it allways slide to the right no matter what arrow you press.
